### ISSUE TITLE
Compiling in windows

### ISSUE THREAD

**Issue by MetricManifold** [wesbarnett/libxdrfile#1]
The ability to compile this library in windows should be added. To compile in Windows 7 with CMake 3.18, I made the following changes in the source code:

- To file `xdrfile.c` I added `typedef int off_t;`
- In file `xdrfile.c` I changed `ftello` to `ftell`
- In file `xdrfile.c` I changed `fseeko` to `fseek`
- To the file `test.c` I added a definition for `M_PI`

Additionally, in the cmake there is a condition that the library `m` is linked only if the platform is not `WIN32`. I also had to make the library `STATIC` instead of `SHARED`.

**Comment by supernova4869** [comment]
What is the value of M_PI in test.c?
